server:
  port: ${PORT:8080}

spring:
  application:
    name: user-service
  datasource:
    username: dev
    password: poridg1803!!!
    url: jdbc:mysql://localhost:3306/students_ll5?characterEncoding=utf8&createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_SERVICE_URL_HOSTNAME:localhost}:${EUREKA_CLIENT_SERVICE_URL_PORT:8761}/eureka/